import React, { useState } from "react";
import { Link, NavLink, Route, Routes, useNavigate, useParams } from "react-router-dom";
import {
  HeartHandshake, LayoutDashboard, Search, Bell, LogOut, Menu, X,
  Package, CheckCircle2, Clock3, Users, FileText, Plus, Upload, Eye,
  ShieldCheck, MapPin, ArrowRight, Heart, ClipboardList, BarChart3,
  Building2, UserCheck, AlertCircle, Settings, Trash2, UserCircle, SlidersHorizontal
} from "lucide-react";

const drives = [
  {id:1,title:"School Supplies for Riverside Elementary",partner:"Riverside Elementary School",location:"Quezon City",category:"School Supplies",needed:120,donated:78,description:"Help provide notebooks, pencils, bags, and other school supplies for students.",image:"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80"},
  {id:2,title:"Food Assistance for Barangay San Isidro",partner:"Barangay San Isidro",location:"Manila",category:"Food",needed:200,donated:135,description:"Food packs for families who need temporary assistance.",image:"https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=900&q=80"},
  {id:3,title:"Hygiene Kits for Youth Center",partner:"Hope Youth Center",location:"Pasig City",category:"Hygiene",needed:100,donated:42,description:"Basic hygiene kits for young people in the community.",image:"https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=900&q=80"}
];

const donations=[
  {id:1,item:"10 notebooks",type:"School supplies",drive:"Riverside Elementary",date:"Sep 08, 2026",status:"Received"},
  {id:2,item:"5 food packs",type:"Food",drive:"Barangay San Isidro",date:"Sep 04, 2026",status:"Distributed"},
  {id:3,item:"3 hygiene kits",type:"Hygiene",drive:"Hope Youth Center",date:"Aug 28, 2026",status:"Recorded"}
];

function Layout({children,role="Donor"}) {
  const [open,setOpen]=useState(false);
  const links=role==="Admin"
    ? [["/admin","Dashboard",LayoutDashboard],["/admin/verification","Verification",UserCheck],["/admin/drives","Drives",Heart],["/admin/reports","Reports",BarChart3],["/admin/profile","Profile",UserCircle]]
    : role==="Partner"
    ? [["/partner","Dashboard",LayoutDashboard],["/partner/create-drive","Create Drive",Plus],["/partner/requests","Requests",ClipboardList],["/partner/distribution","Distribution",Package],["/partner/profile","Profile",UserCircle]]
    : [["/dashboard","Dashboard",LayoutDashboard],["/drives","Donation Drives",Heart],["/my-donations","My Donations",Package],["/notifications","Notifications",Bell],["/profile","Profile",UserCircle]];
  return <div className="app-shell">
    <aside className={`sidebar ${open?"open":""}`}>
      <div className="brand"><div className="brand-icon"><HeartHandshake size={23}/></div><div><strong>ClearGive</strong><span>{role} Portal</span></div></div>
      <nav>{links.map(([to,label,Icon])=><NavLink key={to} to={to} onClick={()=>setOpen(false)}><Icon size={19}/>{label}</NavLink>)}</nav>
      <div className="sidebar-bottom">
        <div className="mini-card"><ShieldCheck size={20}/><div><b>Verified Platform</b><small>Transparent assistance records</small></div></div>
        <Link to="/" className="logout"><LogOut size={18}/> Log out</Link>
      </div>
    </aside>
    {open&&<div className="overlay" onClick={()=>setOpen(false)}/>}
    <main className="main">
      <header className="topbar">
        <button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>
        <div className="search-box"><Search size={18}/><input placeholder="Search..." /></div>
        <div className="top-actions"><button className="icon-btn"><Bell size={19}/><span className="dot"/></button><div className="user-chip"><div className="avatar">{role[0]}</div><span>{role}</span></div></div>
      </header>
      <div className="content">{children}</div>
    </main>
  </div>
}

function Landing(){const nav=useNavigate();return <div className="landing">
  <nav className="landing-nav"><Link to="/" className="brand"><div className="brand-icon"><HeartHandshake size={23}/></div><div><strong>ClearGive</strong><span>Community Assistance</span></div></Link><div className="landing-links"><a href="#how">How it works</a><button className="btn secondary" onClick={()=>nav("/login")}>Log in</button><button className="btn primary" onClick={()=>nav("/register")}>Create account</button></div></nav>
  <section className="hero"><div className="hero-copy"><span className="eyebrow"><ShieldCheck size={15}/> VERIFIED COMMUNITY ASSISTANCE</span><h1>Give with purpose.<br/><span>Help with confidence.</span></h1><p>ClearGive connects donors with verified schools, barangays, communities, and organizations that need assistance.</p><div className="hero-buttons"><button className="btn primary large" onClick={()=>nav("/drives")}>Explore donation drives <ArrowRight size={18}/></button><button className="btn secondary large" onClick={()=>nav("/register")}>Become a donor</button></div><div className="trust-row"><span><CheckCircle2 size={16}/> Verified requests</span><span><CheckCircle2 size={16}/> Donation tracking</span><span><CheckCircle2 size={16}/> Proof of distribution</span></div></div><div className="hero-art"><img src="https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1000&q=80"/><div className="hero-card card-one"><Heart size={24}/><b>320+</b><small>Donations recorded</small></div><div className="hero-card card-two"><CheckCircle2 size={23}/><b>Verified</b><small>Community partner</small></div></div></section>
  <section className="stats-strip"><div><b>24</b><span>Active drives</span></div><div><b>18</b><span>Verified partners</span></div><div><b>320+</b><span>Donations recorded</span></div><div><b>12</b><span>Communities helped</span></div></section>
  <section id="how" className="simple-section"><span className="eyebrow">HOW IT WORKS</span><h2>Simple, organized, transparent.</h2><div className="steps"><div><span>01</span><h3>Choose a drive</h3><p>Browse verified donation drives and see what each community needs.</p></div><div><span>02</span><h3>Record your donation</h3><p>Select the items and quantity you are contributing.</p></div><div><span>03</span><h3>Track the result</h3><p>Follow the status until assistance is received and distributed.</p></div></div></section>
</div>}

function Login(){const nav=useNavigate();return <div className="auth-page"><div className="auth-brand"><Link to="/" className="brand"><div className="brand-icon"><HeartHandshake size={23}/></div><div><strong>ClearGive</strong><span>Community Assistance</span></div></Link></div><div className="auth-box"><h1>Welcome back</h1><p>Choose a demo role to preview the system.</p><div className="demo-roles"><button onClick={()=>nav("/dashboard")}>Donor</button><button onClick={()=>nav("/partner")}>Partner</button><button onClick={()=>nav("/admin")}>Admin</button></div><form onSubmit={e=>{e.preventDefault();nav("/dashboard")}}><label>Email address<input type="email" placeholder="you@example.com" required/></label><label>Password<input type="password" placeholder="Enter your password" required/></label><div className="form-row"><label className="check"><input type="checkbox"/> Remember me</label><a href="#">Forgot password?</a></div><button className="btn primary full">Log in</button></form><p className="auth-footer">Don't have an account? <Link to="/register">Create one</Link></p></div></div>}

function Register(){const nav=useNavigate();return <div className="auth-page"><div className="auth-brand"><Link to="/" className="brand"><div className="brand-icon"><HeartHandshake size={23}/></div><div><strong>ClearGive</strong><span>Community Assistance</span></div></Link></div><div className="auth-box"><h1>Create your account</h1><p>Register as a donor or partner organization.</p><form onSubmit={e=>{e.preventDefault();nav("/dashboard")}}><div className="two-col"><label>First name<input placeholder="First name" required/></label><label>Last name<input placeholder="Last name" required/></label></div><label>Email address<input type="email" placeholder="you@example.com" required/></label><label>Account type<select><option>Donor</option><option>Partner Organization</option></select></label><label>Password<input type="password" placeholder="Create a password" required/></label><label className="check"><input type="checkbox" required/> I agree to the terms and privacy policy.</label><button className="btn primary full">Create account</button></form><p className="auth-footer">Already have an account? <Link to="/login">Log in</Link></p></div></div>}

function Dashboard(){return <Layout role="Donor"><Heading eyebrow="DONOR DASHBOARD" title="Good morning, Donor 👋" text="Here’s a quick look at your ClearGive activity." action={<Link to="/drives" className="btn primary"><Heart size={17}/> Find a drive</Link>}/><div className="metric-grid"><Metric icon={Heart} label="Total donations" value="8" note="+2 this month"/><Metric icon={Package} label="Items contributed" value="46" note="Across 4 drives"/><Metric icon={CheckCircle2} label="Completed" value="5" note="Successfully distributed"/><Metric icon={Clock3} label="In progress" value="3" note="Awaiting updates"/></div><div className="dashboard-grid"><DonationTable/><section className="panel"><div className="panel-head"><div><h2>Notifications</h2><p>Latest updates from your donations.</p></div></div><Notice text="Your food packs were distributed to 25 families."/><Notice text="Riverside Elementary received your notebooks."/><Notice text="A new hygiene drive is available in Pasig."/></section></div></Layout>}

function Metric({icon:Icon,label,value,note}){return <div className="metric"><div className="metric-icon"><Icon size={20}/></div><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Heading({eyebrow,title,text,action}){return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function Notice({text}){return <div className="notice"><Bell size={17}/><span>{text}</span></div>}
function DonationTable(){return <section className="panel"><div className="panel-head"><div><h2>Recent donations</h2><p>Your latest contribution records.</p></div><Link to="/my-donations">View all</Link></div><div className="table-wrap"><table><thead><tr><th>Donation</th><th>Drive</th><th>Date</th><th>Status</th></tr></thead><tbody>{donations.map(d=><tr key={d.id}><td><b>{d.item}</b><small>{d.type}</small></td><td>{d.drive}</td><td>{d.date}</td><td><Status value={d.status}/></td></tr>)}</tbody></table></div></section>}
function Status({value}){let c=value==="Received"||value==="Completed"?"green":value==="Distributed"?"blue":"yellow";return <span className={`status ${c}`}>{value}</span>}

function Drives(){const [cat,setCat]=useState("All");const [query,setQuery]=useState("");const filtered=drives.filter(d=>(cat==="All"||d.category===cat)&&`${d.title} ${d.partner} ${d.location}`.toLowerCase().includes(query.toLowerCase()));return <Layout role="Donor"><Heading eyebrow="DONATION DRIVES" title="Find a drive to support" text="All drives shown here are reviewed and verified by ClearGive administrators."/><div className="drive-tools"><div className="local-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by drive, partner, or location..."/></div><div className="filter-row">{["All","School Supplies","Food","Hygiene"].map(c=><button key={c} className={`filter ${cat===c?"active":""}`} onClick={()=>setCat(c)}>{c}</button>)}</div></div>{filtered.length?<div className="drive-grid">{filtered.map(d=><DriveCard key={d.id} drive={d}/>)}</div>:<section className="panel empty-state"><Search size={28}/><h2>No donation drives found</h2><p>Try another keyword or category.</p></section>}</Layout>}
function DriveCard({drive}){const [donate,setDonate]=useState(false);const [sent,setSent]=useState(false);const pct=Math.min(100,Math.round(drive.donated/drive.needed*100));return <article className="drive-card"><div className="drive-image"><img src={drive.image}/><span><ShieldCheck size={14}/> Verified</span></div><div className="drive-body"><div className="category">{drive.category}</div><h2>{drive.title}</h2><p>{drive.description}</p><Link className="text-link" to={`/drives/${drive.id}`}>View drive details <ArrowRight size={13}/></Link><div className="location"><MapPin size={15}/>{drive.location} · {drive.partner}</div><div className="progress-label"><span>{drive.donated} of {drive.needed} items</span><b>{pct}%</b></div><div className="progress"><span style={{width:`${pct}%`}}/></div>{sent?<div className="success-box"><CheckCircle2 size={17}/> Donation recorded successfully.</div>:<button className="btn primary full" onClick={()=>setDonate(!donate)}><Heart size={16}/> Record a donation</button>}{donate&&!sent&&<div className="donate-box"><label>Item and quantity<input placeholder="e.g. 10 notebooks"/></label><button className="btn secondary full" onClick={()=>{setSent(true);setDonate(false)}}>Submit donation</button></div>}</div></article>}

function DriveDetails({id}){const drive=drives.find(d=>String(d.id)===String(id))||drives[0];const pct=Math.min(100,Math.round(drive.donated/drive.needed*100));return <Layout role="Donor"><Heading eyebrow="DONATION DRIVE DETAILS" title={drive.title} text="Review the verified request before recording your contribution." action={<Link to="/drives" className="btn secondary">Back to drives</Link>}/><div className="detail-grid"><section className="panel detail-card"><img src={drive.image} className="detail-image"/><div className="detail-tags"><Status value="Received"/><span className="verified-pill"><ShieldCheck size={14}/> Verified partner</span></div><h2>{drive.title}</h2><p>{drive.description}</p><div className="detail-meta"><span><Building2 size={16}/>{drive.partner}</span><span><MapPin size={16}/>{drive.location}</span><span><ClipboardList size={16}/>{drive.category}</span></div><h3>What is needed</h3><p>Donors can contribute items in the requested category. The partner will record received and distributed assistance for transparency.</p></section><section className="panel detail-side"><span className="eyebrow">PROGRESS</span><div className="detail-number">{drive.donated} / {drive.needed}</div><p>items recorded</p><div className="progress"><span style={{width:`${pct}%`}}/></div><b>{pct}% funded</b><div className="detail-note"><CheckCircle2 size={17}/><span>Partner verification and distribution proof are part of the ClearGive process.</span></div><Link to="/drives" className="btn primary full"><Heart size={16}/> Record a donation</Link></section></div></Layout>}

function Notifications(){return <Layout role="Donor"><Heading eyebrow="NOTIFICATIONS" title="Your notifications" text="Stay updated on your donation activity and verified community drives."/><section className="panel"><Notice text="Your food packs were distributed to 25 families."/><Notice text="Riverside Elementary received your notebooks."/><Notice text="A new hygiene drive is available in Pasig."/><Notice text="Your recent donation was recorded successfully."/></section></Layout>}

function Profile({role="Donor"}){return <Layout role={role}><Heading eyebrow="ACCOUNT SETTINGS" title={`${role} profile`} text="Manage your basic account information and preferences."/><div className="detail-grid"><section className="panel profile-card"><div className="profile-avatar">{role[0]}</div><h2>{role} Account</h2><p>{role==='Partner'?'Verified community partner account':'ClearGive demo account'}</p><div className="profile-fields"><label>Full name<input defaultValue={role==='Partner'?'Riverside Community Partner':'ClearGive User'}/></label><label>Email address<input type="email" defaultValue="user@cleargive.demo"/></label><label>Contact number<input placeholder="09XX XXX XXXX"/></label></div><button className="btn primary"><CheckCircle2 size={16}/> Save changes</button></section><section className="panel"><div className="panel-head"><div><h2><SlidersHorizontal size={17}/> Preferences</h2><p>Demo controls for the frontend prototype.</p></div></div><label className="setting-row"><span><b>Email notifications</b><small>Receive updates about donations and requests.</small></span><input type="checkbox" defaultChecked/></label><label className="setting-row"><span><b>Activity reminders</b><small>Show reminders for pending actions.</small></span><input type="checkbox" defaultChecked/></label></section></div></Layout>}

function MyDonations(){return <Layout role="Donor"><Heading eyebrow="MY DONATIONS" title="Donation history" text="Track your contributions and their current status."/><section className="panel"><div className="table-wrap"><table><thead><tr><th>Donation</th><th>Drive</th><th>Date</th><th>Status</th><th></th></tr></thead><tbody>{donations.map(d=><tr key={d.id}><td><b>{d.item}</b><small>{d.type}</small></td><td>{d.drive}</td><td>{d.date}</td><td><Status value={d.status}/></td><td><button className="icon-btn"><Eye size={17}/></button></td></tr>)}</tbody></table></div></section></Layout>}

function Partner(){return <Layout role="Partner"><Heading eyebrow="PARTNER DASHBOARD" title="Partner organization" text="Manage your requests, donation drives, and distribution records." action={<Link to="/partner/create-drive" className="btn primary"><Plus size={17}/> Create drive</Link>}/><div className="metric-grid"><Metric icon={FileText} label="Assistance requests" value="4" note="1 pending review"/><Metric icon={Heart} label="Active drives" value="3" note="2 currently collecting"/><Metric icon={Package} label="Donations received" value="86" note="+18 this month"/><Metric icon={Users} label="Beneficiaries helped" value="125" note="Across 5 distributions"/></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>My donation drives</h2><p>Manage active community assistance drives.</p></div><Link to="/partner/create-drive">Add new</Link></div><div className="simple-list"><ListItem title="School Supplies Drive" sub="78 / 120 items" status="Active"/><ListItem title="Food Assistance" sub="135 / 200 items" status="Active"/><ListItem title="Winter Clothing Request" sub="Waiting for admin" status="Pending"/></div></section><section className="panel"><div className="panel-head"><div><h2>Distribution updates</h2><p>Recent proof and beneficiary records.</p></div></div><Notice text="Food packs distributed to 25 families."/><Notice text="3 photos uploaded as proof."/><Notice text="Admin approved your school supplies drive."/></section></div></Layout>}
function ListItem({title,sub,status}){return <div className="list-item"><div className="quick-icon"><Heart size={17}/></div><div><b>{title}</b><small>{sub}</small></div><Status value={status}/></div>}

function CreateDrive(){const [saved,setSaved]=useState(false);return <Layout role="Partner"><Heading eyebrow="DONATION DRIVE MANAGEMENT" title="Create a donation drive" text="Submit the details of the assistance your organization needs."/><section className="panel form-panel">{saved?<div className="big-success"><CheckCircle2 size={35}/><h2>Drive submitted for verification</h2><p>The administrator will review your request before it becomes visible to donors.</p><Link to="/partner" className="btn primary">Back to dashboard</Link></div>:<form className="project-form" onSubmit={e=>{e.preventDefault();setSaved(true)}}><div className="two-col"><label>Drive title<input placeholder="e.g. School Supplies for Grade 6" required/></label><label>Category<select><option>School Supplies</option><option>Food</option><option>Hygiene</option><option>Clothing</option><option>Other</option></select></label></div><label>Description<textarea placeholder="Explain who needs help and what is needed." rows="4" required/></label><div className="two-col"><label>Target quantity<input type="number" placeholder="100" required/></label><label>Location<input placeholder="City / Barangay" required/></label></div><label>Supporting document / request letter<div className="upload-box"><Upload size={22}/><span>Click to upload document</span><small>PDF, JPG or PNG</small><input type="file"/></div></label><button className="btn primary">Submit for verification</button></form>}</section></Layout>}

function PartnerRequests(){return <Layout role="Partner"><Heading eyebrow="ASSISTANCE REQUESTS" title="My requests" text="Monitor requests submitted for administrator verification."/><section className="panel"><div className="table-wrap"><table><thead><tr><th>Request</th><th>Submitted</th><th>Status</th><th>Remarks</th></tr></thead><tbody><tr><td><b>School Supplies 2026</b><small>120 items requested</small></td><td>Sep 09, 2026</td><td><Status value="Approved"/></td><td>Drive can be published.</td></tr><tr><td><b>Food Assistance</b><small>200 food packs</small></td><td>Sep 06, 2026</td><td><Status value="Pending"/></td><td>Under admin review.</td></tr><tr><td><b>Hygiene Kits</b><small>100 kits</small></td><td>Sep 02, 2026</td><td><Status value="Approved"/></td><td>Verified partner request.</td></tr></tbody></table></div></section></Layout>}

function Distribution(){const [done,setDone]=useState(false);return <Layout role="Partner"><Heading eyebrow="DISTRIBUTION AND PROOF" title="Record a distribution" text="Document how received donations were distributed to beneficiaries."/><section className="panel form-panel">{done?<div className="big-success"><CheckCircle2 size={35}/><h2>Distribution saved</h2><p>The distribution record and proof are now ready for admin review.</p><button className="btn primary" onClick={()=>setDone(false)}>Add another record</button></div>:<form className="project-form" onSubmit={e=>{e.preventDefault();setDone(true)}}><label>Donation drive<select><option>Food Assistance for Barangay San Isidro</option><option>School Supplies for Riverside Elementary</option></select></label><div className="two-col"><label>Quantity distributed<input type="number" placeholder="25" required/></label><label>Beneficiaries assisted<input type="number" placeholder="25" required/></label></div><label>Distribution date<input type="date" required/></label><label>Distribution notes<textarea rows="4" placeholder="Describe where and how the items were distributed." required/></label><label>Proof of assistance<div className="upload-box"><Upload size={22}/><span>Upload photos or documents</span><small>Photos help verify the distribution</small><input type="file" multiple/></div></label><button className="btn primary">Save distribution record</button></form>}</section></Layout>}

function Admin(){return <Layout role="Admin"><Heading eyebrow="ADMIN DASHBOARD" title="System overview" text="Review users, verification requests, donation drives, and reports."/><div className="metric-grid"><Metric icon={Users} label="Registered users" value="248" note="+14 this month"/><Metric icon={UserCheck} label="Pending verification" value="6" note="Needs review"/><Metric icon={Heart} label="Active drives" value="24" note="18 verified partners"/><Metric icon={Package} label="Donations recorded" value="320" note="This year"/></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>Needs attention</h2><p>Items that require administrator action.</p></div></div><Notice text="6 partner verification requests are waiting."/><Notice text="3 donation drives need document review."/><Notice text="2 distribution records have new proof uploads."/></section><section className="panel"><div className="panel-head"><div><h2>Recent activity</h2><p>Latest system records.</p></div></div><Notice text="New donor account registered today."/><Notice text="Riverside Elementary drive was approved."/><Notice text="A distribution record was completed."/></section></div></Layout>}

function Verification(){const [items,setItems]=useState([{id:1,name:"Riverside Elementary School",type:"School",date:"Sep 09, 2026",status:"Pending"},{id:2,name:"Hope Youth Center",type:"Organization",date:"Sep 08, 2026",status:"Pending"},{id:3,name:"Barangay San Isidro",type:"Barangay",date:"Sep 07, 2026",status:"Pending"}]);const update=(id,status)=>setItems(items.map(x=>x.id===id?{...x,status}:x));return <Layout role="Admin"><Heading eyebrow="PARTNER VERIFICATION" title="Verify partner organizations" text="Review submitted information and supporting documents before approval."/><section className="panel"><div className="table-wrap"><table><thead><tr><th>Organization</th><th>Type</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.name}</b><small>Documents attached</small></td><td>{x.type}</td><td>{x.date}</td><td><Status value={x.status}/></td><td>{x.status==="Pending"?<div className="action-buttons"><button className="btn small" onClick={()=>update(x.id,"Approved")}><CheckCircle2 size={14}/> Approve</button><button className="btn small danger" onClick={()=>update(x.id,"Rejected")}><AlertCircle size={14}/> Reject</button></div>:<span className="muted">Reviewed</span>}</td></tr>)}</tbody></table></div></section></Layout>}

function AdminDrives(){return <Layout role="Admin"><Heading eyebrow="DRIVE MANAGEMENT" title="Manage donation drives" text="Approve and monitor donation drives submitted by verified partners."/><section className="panel"><div className="table-wrap"><table><thead><tr><th>Drive</th><th>Partner</th><th>Progress</th><th>Status</th><th>Action</th></tr></thead><tbody>{drives.map(d=><tr key={d.id}><td><b>{d.title}</b><small>{d.category}</small></td><td>{d.partner}</td><td>{d.donated} / {d.needed}</td><td><Status value="Active"/></td><td><button className="icon-btn"><Eye size={17}/></button><button className="icon-btn"><Settings size={17}/></button></td></tr>)}</tbody></table></div></section></Layout>}

function Reports(){return <Layout role="Admin"><Heading eyebrow="REPORTS" title="Donation reports" text="Simple summary of donation and distribution activity."/><div className="report-grid"><div className="report-card"><BarChart3/><span>Total donations</span><b>320</b><small>Recorded contributions</small></div><div className="report-card"><Package/><span>Items distributed</span><b>214</b><small>Successfully distributed</small></div><div className="report-card"><Users/><span>Beneficiaries</span><b>486</b><small>People assisted</small></div></div><section className="panel"><div className="panel-head"><div><h2>Monthly activity</h2><p>Sample report for presentation/demo.</p></div><button className="btn secondary"><FileText size={15}/> Export report</button></div><div className="bar-chart"><div style={{height:"55%"}}><span>Jun</span></div><div style={{height:"72%"}}><span>Jul</span></div><div style={{height:"45%"}}><span>Aug</span></div><div style={{height:"90%"}}><span>Sep</span></div></div></section></Layout>}

function DriveDetailsRoute(){const {id}=useParams(); return <DriveDetails id={id}/>;}

function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/drives" element={<Drives/>}/><Route path="/drives/:id" element={<DriveDetailsRoute/>}/><Route path="/my-donations" element={<MyDonations/>}/><Route path="/notifications" element={<Notifications/>}/><Route path="/profile" element={<Profile/>}/><Route path="/partner" element={<Partner/>}/><Route path="/partner/create-drive" element={<CreateDrive/>}/><Route path="/partner/requests" element={<PartnerRequests/>}/><Route path="/partner/distribution" element={<Distribution/>}/><Route path="/partner/profile" element={<Profile role="Partner"/>}/><Route path="/admin" element={<Admin/>}/><Route path="/admin/verification" element={<Verification/>}/><Route path="/admin/drives" element={<AdminDrives/>}/><Route path="/admin/reports" element={<Reports/>}/><Route path="/admin/profile" element={<Profile role="Admin"/>}/></Routes>}
export default App;